name: Deploy Project
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: list contents
              run: ls -al
            - name: Get code
              uses: actions/checkout@v3
            - name: list contents again!
              run: ls -al              
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Build project
          run: npm run build
        - name: Deploy
          run: echo "Deploying ..."
    finish:
      needs: [test, deploy]
      runs-on: ubuntu-latest
      steps:
        - name: Finish
          run: echo "Finished!"
            

